### ISSUE TITLE
[FEATURE] Add printer drivers & cups

### ISSUE THREAD

**Issue by PSGitHubUser1** [mylinuxforwork/dotfiles#28] opened 2024-07-22 11:30 UTC
## $ Describe your feature

I would like to have a printer configs, in your dotfiles, so that anybody can directly configure their printer too...

[Here](https://gist.github.com/PSGitHubUser1/4574b07dd809f83e675bf914a19ecfb7) is my gist, it is just a `template` for you to start with, it will be beneficial for others.. like me or newbies to Arch. To configure their printers.

My gist installs system-config-printer, cups & its relatives.. also it enables & start cups with systemctl too, made a choice which asks user to install `$Printer_Company_Drivers` like Epson or Canon printer drivers..

**Comment by mylinuxforwork** [comment] 2024-07-22 12:23
Thanks for sharing your idea. Unfortunately I don't have a printer ;-) That's why I cannot test it currently in my environment. 

Maybe someone else can test this script?

**Comment by PSGitHubUser1** [comment] 2024-07-23 00:40
> Thanks for sharing your idea. Unfortunately I don't have a printer ;-) That's why I cannot test it currently in my environment. 
> 
> Maybe someone else can test this script?

Gotta ask somebody else then..

**Comment by eljejer** [comment] 2024-07-25 07:34
> Thanks for sharing your idea. Unfortunately I don't have a printer ;-) That's why I cannot test it currently in my environment.
> 
> Maybe someone else can test this script?

@mylinuxforwork  I have an HP printer and could test things with it...

**Comment by krystalsavage** [comment] 2024-07-25 22:57
I used one of the scripts created by Mr. Raabe to create my own script for installing printers. I am not sure how to 
attach here, but it is a quick sample. I personally love the way he scripts everything -  sehr schöne!!! The problem is that there are many printers out there and the script would need to be edited for your own printers.

[installprinters.md](https://github.com/user-attachments/files/16384346/installprinters.md)

**Comment by PSGitHubUser1** [comment] 2024-07-26 11:46
> I used one of the scripts created by Mr. Raabe to create my own script for installing printers. I am not sure how to 
> attach here, but it is a quick sample. I personally love the way he scripts everything -  sehr schöne!!! The problem is that there are many printers out there and the script would need to be edited for your own printers.
> 
> [installprinters.md](https://github.com/user-attachments/files/16384346/installprinters.md)
> 

Well have you checked my script though?
I think its a good idea to have Printer installation during Dotfiles installation.. (of course, asking first from user). Just out-of-the-box.

**Comment by mylinuxforwork** [comment] 2024-08-05 18:54
@eljejer Any Updates on this? Can we close this issue?

**Comment by eljejer** [comment] 2024-08-05 21:34
> @eljejer Any Updates on this? Can we close this issue?

@mylinuxforwork I did not come around yet to testing the add printer & cups installation. I will try to look into it this week...

**Comment by mylinuxforwork** [comment] 2024-08-06 05:21
> > @eljejer Any Updates on this? Can we close this issue?
> 
> @mylinuxforwork I did not come around yet to testing the add printer & cups installation. I will try to look into it this week...

Thanks for your feedback.

**Comment by PSGitHubUser1** [comment] 2024-08-15 02:32
@eljejer 
@mylinuxforwork 

Any update on this?

**Comment by eljejer** [comment] 2024-08-15 05:49
> @eljejer @mylinuxforwork
> 
> Any update on this?

Unfortunately no, not yet. The plan is to look into it coming weekend

**Comment by eljejer** [comment] 2024-08-18 10:30
@mylinuxforwork today I tested the script that @PSGitHubUser1 linked above. I can confirm that I was able to run the script, choose the drivers for my HP printer, add the printer, and print a test-page. So for a HP printer the script works well, thanks!

**Comment by PSGitHubUser1** [comment] 2024-08-18 10:49
> @mylinuxforwork today I tested the script that @PSGitHubUser1 linked above. I can confirm that I was able to run the script, choose the drivers for my HP printer, add the printer, and print a test-page. So for a HP printer the script works well, thanks!

@mylinuxforwork it works but as I said it's just a template. Can you configure it to look nice with `gum` (I guess?) and Implement it in pre-installation OR post-installation of dotfiles?

**Comment by PSGitHubUser1** [comment] 2024-08-18 12:21
> So for a HP printer the script works well, thanks!

Yeah. I am happy that it helped, I never installed the Printer drivers on Arch. It was very frustrating for me as I had a habit of GUI like in Ubuntu or Fedora. 

And after facing it, I made this so that you won't get frustrated and give up 3-4 times like me.

Also, (in script), if you choose 'Other' printer, you have the option to enter the package name of that printer. So, it's not just limited to big guys like HP or Epson.

**Comment by mylinuxforwork** [comment] 2024-08-19 18:54
Sounds great. I will have a look into the script.

**Comment by mylinuxforwork** [comment] 2024-08-19 19:00
I would remove the check for yay and the snapshot. yay is required for the dotfiles anyway. 

The rest looks fine.

Will add the script to the script folder and link it from the welcome app.

**Closed** 2024-08-21 12:59 UTC
Labels: enhancement

**Comment by PSGitHubUser1** [comment] 2024-08-21 15:28
> @krystalsavage I have added your script to the main branch for the upcoming 2.9.6.
> https://github.com/mylinuxforwork/dotfiles/blob/main/share/dotfiles/.config/ml4w/scripts/installprinters.sh
> 
> The Printer drivers can be managed in 
> https://github.com/mylinuxforwork/dotfiles/blob/main/share/dotfiles/.config/ml4w/settings/printer-drivers.sh
> 
> Thanks again.

Ohk. But who's @krystalsavage
